### ISSUE TITLE
Compare training behaviour (test/ validation)

### ISSUE THREAD

**Issue by Dutzel** [NVlabs/Deep_Object_Pose#100]
Hello, I would like to see the impact of different datasets on the DOPE-Network while/ or after learning. Therefor I started a training with a path for --traindata to get some content into my loss_train.csv and loss_test.csv, but I cant see a learning progress in that data.

How did you check the quality of your trained models?

**Comment by TontonTremblay** [comment]
We have other scripts to test the neural network that we did not share publicly. Since the network is meant to work on wild poses and objects. It was mainly tested on our robotics system. Sorry my help is limited here.

**Comment by Dutzel** [comment]
Okay, thanks for your great work anyway :)
