### ISSUE TITLE
can i get some real testing images for all the products ? It would be really helpful.

### ISSUE THREAD

**Issue by ravan786** [NVlabs/Deep_Object_Pose#110]
can i get some real testing images for all the products ? It would be really helpful.
Thanks

**Comment by mintar** [comment]
Here you go: https://zenodo.org/record/2579172

**Comment by ravan786** [comment]
thanks a lot man

**Comment by ravan786** [comment]
@mintar I am sorry but I can’t resist to ask. Can you please tell me the reason for the QR code patterns on the table??

**Comment by mintar** [comment]
The marker board on the table consists of ArUco markers. We used the marker board to estimate the camera pose in each frame. That way, we only had to label the ground truth poses of all objects in the scene once (in the global coordinate system defined by the marker board) and could then automatically transform them into the camera coordinate system for each frame.

By the way, I have an ICRA 2020 paper about the dataset. I still have to upload it to arXiV, but in the meantime, I can send it to you by email if you're interested.

**Comment by ravan786** [comment]
> The marker board on the table consists of ArUco markers. We used the marker board to estimate the camera pose in each frame. That way, we only had to label the ground truth poses of all objects in the scene once (in the global coordinate system defined by the marker board) and could then automatically transform them into the camera coordinate system for each frame.
> 
> By the way, I have an ICRA 2020 paper about the dataset. I still have to upload it to arXiV, but in the meantime, I can send it to you by email if you're interested.

@mintar that would be great! please mail it to krishna.ritesh94@gmail.com
