### ISSUE TITLE
Is it possible to directly estimate poses from the bounding boxes?

### ISSUE THREAD

**Issue by syunni33** [NVlabs/Deep_Object_Pose#112]
Hi,

Currently, I haven't checked or applied for your work in my environment yet. 

However, before applying to mine, I want to know whether it is possible to directly estimate poses from the RGB images with bounding boxes like an image below.

<img width="400" alt="dope_objects" src="https://user-images.githubusercontent.com/46441184/79840224-9ac1c000-83f0-11ea-8957-55727ef109b4.png">

Is it possible to get the poses from the images that both RGB and bounding boxes are combined as an input, rather to use RGB images as you did?

**Comment by TontonTremblay** [comment]
Yes you will get bounding boxes and poses like in the image.

**Comment by syunni33** [comment]
It seems that I didn't explain well. I mean I want to use object bounding boxes as an input, not as an output.
Input: RGB image + object bounding boxes (bboxes are contained in the RGB images)
Output: pose

**Comment by TontonTremblay** [comment]
You should be able to predict something, but I dont think it is going to be that precise. You wont be able to get the orientation, you can ruffly get the translation from the bbox.

**Comment by syunni33** [comment]
Thank you!

**Comment by PerceptMD** [comment]
I was thinking about cutting out the depth image to the predicted 2D bounding box size before trying to estimate any pose, as this would be less data to process.

@TontonTremblay why exactly will this approach not be able to get the orientation?

**Comment by TontonTremblay** [comment]
Yeah you can for sure do that, I have seen system like this working without any problems.
