### ISSUE TITLE
question about use of VGG19 in network

### ISSUE THREAD

**Issue by huckl3b3rry87** [NVlabs/Deep_Object_Pose#113]
In the DOPE paper it says that the first 10 layers of VGG19 are used, but in the [training script](https://github.com/NVlabs/Deep_Object_Pose/blob/master/scripts/train.py#L111) it looks like the first 24 layers are used. Was the code updated after the paper was written? Or am I missing something?

Thanks!

**Comment by TontonTremblay** [comment]
Some of these layers are activation and pooling layers I think. I might have miss counted the layers as well when writing the paper, if it is the case I am sorry. We did not change the architecture since the paper to now.

**Comment by huckl3b3rry87** [comment]
@TontonTremblay thank you for the response!
