### ISSUE TITLE
Short question to the weights

### ISSUE THREAD

**Issue by Dutzel** [NVlabs/Deep_Object_Pose#118]
Hello again :) I just wanted to ask you how the [weights](https://drive.google.com/drive/folders/1DfoA3m_Bm0fW8tOWXGVxi4ETlLEAgmcg) in the source you linked in this project were trained. Were they trained with the fat dataset or were they trained with another DR+FR dataset?

Thank you 👍

**Comment by TontonTremblay** [comment]
Most are dr+fat except the toilet cleaner which is DR only.

**Comment by Dutzel** [comment]
Ah okay, thank you very much! Was the number of dr images the same as the fat ones? Like 50% DR and 50% photorealistic?

**Comment by TontonTremblay** [comment]
yes something like this.

**Comment by Dutzel** [comment]
Thank you :)
