### ISSUE TITLE
How to display images like the example

### ISSUE THREAD

**Issue by ZZ-111** [NVlabs/Deep_Object_Pose#134]
First of all, thank you for this great open source project.
My questions are:
How to display images like the example(coordinates. boxes.mask in same image):
<img width="234" alt="dope_objects" src="https://user-images.githubusercontent.com/55341540/87784324-a0506a00-c868-11ea-8a6a-3b3f89ebaf8b.png">
I can only show them separately like this:

If the camera subscribes image topic /dope/rgb_points ,it shows like this:

**Comment by ZZ-111** [comment]
![2020-07-22 20-32-35屏幕截图](https://user-images.githubusercontent.com/55341540/88177179-0408d780-cc5b-11ea-8081-1ddfbf97c119.png)
I modified some code, which now display borders and coordinates, but how to make them exactly the same as the sample pictures (borders, color coordinates, mask).

**Comment by mintar** [comment]
I think the sample pictures were generated using [NVDU](https://github.com/NVIDIA/Dataset_Utilities).

Your RViz screenshot already looks very good. What do you want to do differently?

* Remove the text? That's possible by disabling some namespace in the "MarkerArray" Display.
* Make the coordinate axes more colorful? Then you'll have to rotate the 3D view in RViz so that you look at the object from roughly the same direction as the camera. This is because RViz renders a light behind the camera, and in your screenshot you look the opposite direction, so that the coordinate axes are in the shadow (they are lighted from the opposite side).

**Comment by ZZ-111** [comment]
> I think the sample pictures were generated using [NVDU](https://github.com/NVIDIA/Dataset_Utilities).
> 
> Your RViz screenshot already looks very good. What do you want to do differently?
> 
> * Remove the text? That's possible by disabling some namespace in the "MarkerArray" Display.
> * Make the coordinate axes more colorful? Then you'll have to rotate the 3D view in RViz so that you look at the object from roughly the same direction as the camera. This is because RViz renders a light behind the camera, and in your screenshot you look the opposite direction, so that the coordinate axes are in the shadow (they are lighted from the opposite side).

Thank you for your help. Now the coordinate system is colorful!
![2020-07-23 17-40-17屏幕截图](https://user-images.githubusercontent.com/55341540/88272643-9bc5fe80-cd0b-11ea-803c-6f6f028d1346.png)

Another problem is that if i want to make the picture exactly the same as the sample picture,do I need to use NVDU?

**Comment by mintar** [comment]
What do you mean by "exactly the same"?

**Comment by ZZ-111** [comment]
> What do you mean by "exactly the same"?

I can see that the coordinates on this graph are not fully displayed, and some of them are hidden.
![2020-07-23 18-00-08屏幕截图](https://user-images.githubusercontent.com/55341540/88274600-8b635300-cd0e-11ea-9918-b97efa457cea.png)

**Comment by mintar** [comment]
I think you will have to use NVDU for this. But then you'll have to write some code to export the detections to NVDU format.

**Comment by ZZ-111** [comment]
> 我认为您必须为此使用NVDU。但是随后您必须编写一些代码以将检测结果导出为NVDU格式。

Ok.Thank you!

**Comment by ZZ-111** [comment]
> I think you will have to use NVDU for this. But then you'll have to write some code to export the detections to NVDU format.

Ok.Thank you!
