### ISSUE TITLE
Is there a way to use it with ROS 2?

### ISSUE THREAD

**Issue by sebastian-ruiz** [NVlabs/Deep_Object_Pose#136]
Has anyone had any luck getting it to work with ROS 2? I have seen that there is a [ros 1 to ros 2 bridge](https://github.com/ros2/ros1_bridge). Maybe this is an option?

**Comment by nv-jeff** [comment]
We have not yet invested the time in bringing this to ROS 2.  However, an update was just pushed that allows DOPE to run with Python 3 in ROS Noetic, if that is of any help.
