### ISSUE TITLE
ModuleNotFoundError 'camera_info_manager' when running in docker

### ISSUE THREAD

**Issue by HUSH-Wang** [NVlabs/Deep_Object_Pose#150]
I was running DOPE in a Docker Container.
When running cmd `roslaunch dope camera.launch` in step 2 Start camera node.
There is an error said ModuleNotFoundError: No module named 'camera_info_manager'.
Is there anything I missed?

![image](https://user-images.githubusercontent.com/22000777/99142184-ce667f00-268d-11eb-81bf-f2cd14a07e7c.png)

**Comment by TontonTremblay** [comment]
@nv-jeff do you have an idea?

**Comment by mintar** [comment]
When the Dockerfile was upgraded to ROS Noetic, the "rosdep" lines were removed:

https://github.com/NVlabs/Deep_Object_Pose/commit/6b78c466b3d739d3f6cc27c4680df179a3c8f53d#diff-fd78dacf04884694bb696c4f604cc27de9f3372c43531517a3205bcbcc28eee1L60-L63

Running rosdep takes care of automatically installing all dependencies that are specified in the `package.xml`. So either you put these lines back in (that would be the clean preferred version), or you manually install the package `ros-noetic-camera-info-manager-py`.

**Comment by HUSH-Wang** [comment]
Thank you so much. It works.
