### ISSUE TITLE
Symmetric Object

### ISSUE THREAD

**Issue by blaine141** [NVlabs/Deep_Object_Pose#152]
I was wondering if there would be any problems with radially symmetric objects. For my robotics competition we have symmetric objects we need to interact with. Here is an example NDDS sample. The object is the red thing. 

![004505](https://user-images.githubusercontent.com/6363539/102515373-afc42100-405b-11eb-83d9-56f3410654f2.png)

Can DOPE learn symmetric objects? Just want to know before I put in the effort training.

**Comment by TontonTremblay** [comment]
DOPE wont deal with symmetries out of the box, but if you are careful in how you generate your data, specially the poses you show during training you can deal with symmetries. Think about just showing certain faces of the cuboid.
