### ISSUE TITLE
Display affinity and belief maps

### ISSUE THREAD

**Issue by Richo400** [NVlabs/Deep_Object_Pose#169]
Hi, awesome job with DOPE , I find myself testing your work and have found the pose with the ROS inference with the box of cookies. I would like to see the belief and affinity maps, in what way do I display those screens. 

Another question, can the network display only object detection or object segmentation?
Thank you very much

**Comment by TontonTremblay** [comment]
Thank you! If you look around the issues I have shared in the past some snippet of code to do what you are asking.

**Comment by TontonTremblay** [comment]
You should look in the different closed/open issues.
