### ISSUE TITLE
training single color and symmetry object failed

### ISSUE THREAD

**Issue by Chi-Ruei** [NVlabs/Deep_Object_Pose#180]
I try to train objects as below.
and the result is really bad 
Is dope not suitable for training such items?
![Timing_Pulley_Large sim input](https://user-images.githubusercontent.com/66268851/126512040-0ffde4cb-87bd-4435-9574-4da8d58f65bf.jpg)
![Timing_Pulley_Large real](https://user-images.githubusercontent.com/66268851/126512164-0d8f8681-f39f-4d5c-a15d-5599a893cfd2.png)
![tensorboard Timing_Pulley_Large](https://user-images.githubusercontent.com/66268851/126512184-75751896-5362-414a-8ebb-1a97f82e5d83.png)

**Comment by mintar** [comment]
The problem is that your object is symmetric. That's solvable, but takes some work. Search the existing issues (also closed ones) for "symmetry":

https://github.com/NVlabs/Deep_Object_Pose/issues?q=is%3Aissue+symmetry
