### ISSUE TITLE
Rotation Axes

### ISSUE THREAD

**Issue by aditya2592** [NVlabs/Deep_Object_Pose#20]
Is it possible to know the exact orientation of the axes in with respect to which we get the rotation values during inference ?

**Comment by TontonTremblay** [comment]
I am not sure I understand the question, could give me an example?

**Comment by aditya2592** [comment]
Hi @TontonTremblay 
I wanted to ask if the rotations in the annotated FAT dataset and those predicted by DOPE are in the camera frame or world frame

**Comment by TontonTremblay** [comment]
I am not sure, this should be quite easy to double check, just run DOPE with http://wiki.ros.org/image_publisher feeding FAT images and check the quaternion. I would not be surprised if you need to apply a 90 degree rotation.

**Comment by mintar** [comment]
The poses are in the camera frame.

**Comment by aditya2592** [comment]
Thanks @mintar. We are also given a camera pose in the world frame in the FAT dataset. So if I need the object pose in world frame, I can get it just by multiplying object pose in camera frame by the camera pose in world frame right?

**Comment by mintar** [comment]
Right! :)

**Comment by aditya2592** [comment]
Is there an expected orientation of the worldframe in FAT images with respect to gravity? Like will z be pointing upwards from the ground or be parallel to the ground? Or can the worldframe can be any random point with a random orientation in the scene?
I am trying to visualize poses in the worldframe of FAT images and wanted to make sure I am getting the right results.

**Comment by UniqueVN** [comment]
The FAT dataset use OpenCV coordinate system: Z - forward, X - right, Y - down. You can see the detail here: http://homepages.inf.ed.ac.uk/rbf/CVonline/LOCAL_COPIES/OWENS/LECT9/node2.html

**Comment by aditya2592** [comment]
So that means in all scenes, Y axis would be perpendicular to the ground and pointing downwards?

**Comment by UniqueVN** [comment]
Yes, that's right. In the object's location, if Y is > 0, it mean the object is below the center of the view.

**Comment by IbrahimMCode** [comment]
Hello, 
Is it possible to visualize the Rotation Axes with the predicted DOPE Bounding boxes similar to the Figure3 in the Paper?
Thank you
