### ISSUE TITLE
Required synthetic dataset to detect specific object

### ISSUE THREAD

**Issue by mhibdr** [NVlabs/Deep_Object_Pose#217]
I am new in AI and object pose estimation field, I am trying to gentert data set using Unity Engine , i would like to ask how should the genereteted dataset looks like , i mean should its contains left and right prespectiv of the object.
I found in wiki this sentenc "Create a domain randomization with scene with your object being exported." and i think that mean the data should be random from every prespectiv of the object?

I hope you can help,

**Comment by TontonTremblay** [comment]
You can use the nvisii script or the ndds software. There are other posts in the issues discussing how to generate data.
