### ISSUE TITLE
need help --custom object training

### ISSUE THREAD

**Issue by HiHiAllen** [NVlabs/Deep_Object_Pose#232]
HI, i have  some doubt about my custom object training .Using NDDS, i generated  20k  images to train the net and run it  38 epochs (from epoch 20-38 , the loss fluctuates around  0.0018 ， so i shut it down )
Then i input several images from those  20k  images , and i got their beliefs maps ,it seems quite good ,i strongly believe that the training works.
Here are some belief maps:
![选区_064](https://user-images.githubusercontent.com/93784238/158962019-c21edf1f-c655-438d-98e8-072de7979c2c.png)
![选区_055](https://user-images.githubusercontent.com/93784238/158962020-b30b7d06-af49-47b8-a03b-323fbb26234a.png)
![选区_056](https://user-images.githubusercontent.com/93784238/158962026-1f01bc0e-bbe0-4f32-8ed0-b4ed915da508.png)
![选区_059](https://user-images.githubusercontent.com/93784238/158962018-be67dd47-2232-478e-82db-4a3bacfa264c.png)
![选区_058](https://user-images.githubusercontent.com/93784238/158962058-ea1a3e1c-58a6-4d51-ab80-b9afae56020e.png)

BUT ,when i input some images photographed by my camera (astra pro  640*480), target cant be identified .
Here are some belief maps:
 
![选区_065](https://user-images.githubusercontent.com/93784238/158962487-a59c5f3a-4520-4b2f-827f-c5fc3ef5f3e3.png)
![选区_066](https://user-images.githubusercontent.com/93784238/158962494-ba8f0d72-5ca1-435d-b7ef-8c5ba4fe1a7f.png)
![选区_067](https://user-images.githubusercontent.com/93784238/158962497-ab3e6fd9-bb5a-479e-bbe8-3b0ddf8a2e00.png)

so,whats your opinion  , do i need more images to train the net ?  is 50k enough?  or some else problems?  Thanks for any help.

**Comment by TontonTremblay** [comment]
It looks like there might be a symmetry on the object. I cannot see very well from my phone. But looking at the output from the belief maps I would think there is a sym.

**Comment by mintar** [comment]
On the PC, it doesn't look like there is a rotational symmetry, only a mirror symmetry which should be fine.

**Comment by HiHiAllen** [comment]
> It looks like there might be a symmetry on the object. I cannot see very well from my phone. But looking at the output from the belief maps I would think there is

**Comment by HiHiAllen** [comment]
thanks , i wil try to train a new one to make a comparison.
