### ISSUE TITLE
Unable to Detect Custom Object/ Produce Belief Maps

### ISSUE THREAD

**Issue by BazUCD** [NVlabs/Deep_Object_Pose#238]
Hi I am currently trying to train a custom object (a spanner) for detection with DOPE on a single GPU. After training for 3 Epochs using 20k domain randomized images I was unable to get any detection and I noticed that my loss was far too small from the beginning. 

![image](https://user-images.githubusercontent.com/99204767/160599334-673cda34-b075-489b-a0e3-42cd2af48bd8.png)
the arguments I used for my train.py were as follows:

python train.py --gpuids 0 --batchsize 4 --epochs 3 --data /home/user/Dataset_Synthesizer/Source/NVCapturedData/Spanner1/Spanner1 --namefile Spanner1 --object Spanner1 --outf Spanner

and my object_settings.json is:
![image](https://user-images.githubusercontent.com/99204767/160599659-2a0ac392-f6fb-4f3a-a1eb-d37f11e0f611.png)
I am unsure of what I am doing wrong and I was also wondering how I can develop some belief maps to see what the training is producing. Any help would be greatly appreciated.

**Comment by TontonTremblay** [comment]
I believe the tensorboard of train2.py will have the belief maps. I think the original train might have them as well. Otherwise, I would browse the issues to see how people do it. The code is embedded somewhere on the repo. 

Also without seeing the output I do not think I can help you much. Moreover I do not think I can help much if you do not share training images.

**Comment by BazUCD** [comment]
> I believe the tensorboard of train2.py will have the belief maps. I think the original train might have them as well. Otherwise, I would browse the issues to see how people do it. The code is embedded somewhere on the repo.
> 
> Also without seeing the output I do not think I can help you much. Moreover I do not think I can help much if you do not share training images.

Hi @TontonTremblay thanks a million for your quick reply. I have attached some new images that I have been using to train in a spanner. What output should I provide as well?
![000000](https://user-images.githubusercontent.com/99204767/160779631-71f7a390-16d9-4860-93e2-49fc609bebcc.png)
![000000 depth 16](https://user-images.githubusercontent.com/99204767/160779654-6ad74b87-7208-4af3-86f7-dffc2e183aba.png)

**Comment by BazUCD** [comment]
![000073](https://user-images.githubusercontent.com/99204767/160780143-8b4ed145-7077-4516-940c-59bfb0fec538.png)
![000073 depth 16](https://user-images.githubusercontent.com/99204767/160780159-870422c3-10ec-413a-a7ab-4f1dfc04742b.png)

**Comment by TontonTremblay** [comment]
The wrench has a symmetry, so it might be causing confusion. We are working on a PR to help with that. You should check the merge requests. Without more debugging views of what is going on, I am not sure I can help much more.
