### ISSUE TITLE
need help for coding

### ISSUE THREAD

**Issue by kooshyarkosari** [NVlabs/Deep_Object_Pose#240]
Hello

I have downloaded the Ycb-video Dataset, I want to read the images directly from the file on my PC  then run the DOPE and see the poses of the object instead of using cameras, ROS, and so on, which part of the code must be modified? ( detector, inferences,... ) How can I change it? There is any sample code for this task?

Thanks in advance

**Comment by TontonTremblay** [comment]
https://github.com/NVlabs/Deep_Object_Pose/blob/master/scripts/train2/inference.py check this file. This is inference without ros.

**Comment by TontonTremblay** [comment]
After that I think in one other issue I shared how I computed the ADD. But you can use the code Yu wrote.
