### ISSUE TITLE
Publish "NaN" values when object not detected

### ISSUE THREAD

**Issue by erikkockar** [NVlabs/Deep_Object_Pose#245]
Hi guys, 

I have a question regarding publishing values. 
If I do not detect any object in current image I would like to always publish some specific values. 

So for example my object of interest is not detected in the current image, DOPE will be still publishing some hardcoded data for example zeros. Where should I take look in code i am a bit lost. This is maybe more ROS question maybe there is some easy way ? 

Thanks

**Comment by mintar** [comment]
DOPE already does that! For every input image that DOPE processes, one detected_objects message is published. If no objects are detected, the detected_objects array is empty.

**Comment by TontonTremblay** [comment]
https://github.com/NVlabs/Deep_Object_Pose/blob/master/nodes/dope#L260 specifically the logic is here, you can see the messages getting created per object.
