### ISSUE TITLE
Unable to load object from YCB dataset

### ISSUE THREAD

**Issue by rahulram70** [NVlabs/Deep_Object_Pose#246]
Hello.

I'm trying to generate custom dataset using objects from the YCB dataset. To do so, I downloaded the Gelatin Box google 16k files from http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/ and put them in the ~/catkin_ws/src/dope/scripts/nvisii_data_gen/models directory. I then ran the following command "python single_video_pybullet.py --nb_frames 1 --scale 0.01". 

The terminal states the Gelatin Box and Ketchup was loaded. The ketchup bottles appear in the image, but the Gelatin Box is now where to be found. There is also no entries of the Gelatin Box in the corresponding json. I then tried loading the gelatin textured.obj via the --path_single_obj parameter, but all I got was RuntimeError: Error: parent is empty.

If it helps, I'm running this on an Ubuntu 20.04 machine. Any help would be appreciated, thank you.

**Comment by rahulram70** [comment]
Yes I did, and it didn't work. Even if my object did not appear in the image due to the scale, there should still be an entry in the json file, correct?

**Comment by TontonTremblay** [comment]
Did you try `--interactive` ?

**Comment by rahulram70** [comment]
I tried, and I couldn't find the tennis ball. I reverted to a previous commit and was able to successfully load the YCB objects.

**Comment by mintar** [comment]
So what was the previous commit where it worked?

Regarding the `RuntimeError: Error: parent is empty` with `--path_single_obj`: That's an unrelated problem and discussed in #244.

**Comment by rahulram70** [comment]
I switched to commit a25e028 since I didn't need object symmetry. I did not try the numerous commits after a25e028.
