### ISSUE TITLE
Training at starting epoch

### ISSUE THREAD

**Issue by CorbinFerrie** [NVlabs/Deep_Object_Pose#250]
Hello,
I was wondering if it was possible to begin training starting at a previous epoch.
I am running into stability issues on my PC which causes the training script (my entire PC) to crash randomly at times.
For example, if I trained up to 20 epochs and my PC crashes, is it possible to begin training from the 20th epoch vs starting over again?
This would save me days of headache.
Thanks

**Comment by mintar** [comment]
Yes! The training script saves the weights file (`*.pth`) after each epoch. You can resume training by adding `--net <path-to-latest-pth-file>` to your training script command.
