### ISSUE TITLE
Training data of Tomato Sauce

### ISSUE THREAD

**Issue by Linhhongduc** [NVlabs/Deep_Object_Pose#291]
Hello
I would like to ask if the image data you used to train the tomato sauce recognition was taken from any data other than the Hope dataset? Because in HOPE I only see 45 RGB images, while the article says 60k images are needed. Thank you

**Comment by TontonTremblay** [comment]
You know what I am not sure! I do not remember fully where this 45k set is from. I might have re-render these for someone that asked for them. I am not sure. I render the HOPE dataset using nvisii rendering script in this repo, so you could top it off with 15k images to math.

**Comment by Linhhongduc** [comment]
Oh thank you😁
