### ISSUE TITLE
Questions Regarding inference file generation

### ISSUE THREAD

**Issue by ArghyaChatterjee** [NVlabs/Deep_Object_Pose#294]
Hi,

I had a question regarding the inference file generation after the training. I used the train.py script from train2 folder. I can see the file looks different than the default one. What's the reason for that  and is that a problem ? The one that I generated is ironbar_02.pth and the ones that were already there are the other ones that I downloaded, they look different than the one that is generated by me.

![Screenshot from 2023-04-08 14-05-11](https://user-images.githubusercontent.com/28845357/230738583-061ce2ee-baa4-4328-80f0-b955dc22baee.png)

**Comment by TontonTremblay** [comment]
I am not sure why they are different visually. It is a good question. Maybe torch changed the way it dealt with pth filing.

**Comment by TontonTremblay** [comment]
if it is still running I would say do not worry about it.

**Comment by ArghyaChatterjee** [comment]
Great, thanks for the confirmation.
