### ISSUE TITLE
data for train2.py

### ISSUE THREAD

**Issue by hsisfree** [NVlabs/Deep_Object_Pose#316]
I'm using train2.py in windows 10, jupyter lab.
Do I have to generate dataset for train?? or I can use dataset uploaded???

**Comment by hsisfree** [comment]
> _No description provided._

**Comment by TontonTremblay** [comment]
I think there are some data examples, but you would have to generate your own data.

**Comment by hsisfree** [comment]
I downloaded data from https://github.com/NVlabs/Deep_Object_Pose/issues/155#issuecomment-791148200.
And I run python -m torch.distributed.launch --nproc_per_node=1 train.py --network dope --epochs 2 --batchsize 10 --outf tmp/ --data ../nvisii_data_gen/output/output_example/
command. But I got error like this
![result](https://github.com/NVlabs/Deep_Object_Pose/assets/143778650/e73d5624-04e3-4b29-bd58-a43d13b7b084)

**Comment by hsisfree** [comment]
> I think there are some data examples, but you would have to generate your own data.

I downloaded data from https://github.com/NVlabs/Deep_Object_Pose/issues/155#issuecomment-791148200.
And I run python -m torch.distributed.launch --nproc_per_node=1 train.py --network dope --epochs 2 --batchsize 10 --outf tmp/ --data ../nvisii_data_gen/output/output_example/
command. But I got error like this
![result](https://github.com/NVlabs/Deep_Object_Pose/assets/143778650/ce41e84c-59fd-4940-b229-445963c158ff)
