### ISSUE TITLE
Train with FAT data

### ISSUE THREAD

**Issue by hsisfree** [NVlabs/Deep_Object_Pose#324]
Hi, I'm trying to use fat dataset instead creating my own data.
I also changed utils_dope.py to load projected_cuboid and projected_cuboid_centroid.
I'm using train.py at train2 but I got error messages "NaN or Inf found in input tensor."
![오류2](https://github.com/NVlabs/Deep_Object_Pose/assets/143778650/3b4a2803-d8e7-4a83-870f-20d4a91efa15)

I tried to find where this error came out.
I put "print(checkpoint0)"~"print(checkpoint8)" between the code that write.add_image() at train.py.
![오류 1](https://github.com/NVlabs/Deep_Object_Pose/assets/143778650/ab2689c6-297c-44f9-a5fe-cbadb0b96f0a)

I checked tensorboard. The images(train_Belief_ground_truth, train_Belief_guess, train_input) are stored 7 times. I trained 10 epoch. Stored 1,2,3,4,5,7,10 step.
![오류3](https://github.com/NVlabs/Deep_Object_Pose/assets/143778650/3cffe8f2-0bb7-4263-a7dc-e5e446f234d4)
I check steps but the number of steps are not constant....
Can I ignore this error if I will not use tensorboard?? If I have to edit the code can you give me any help please?
Additionally can I erase this part(write.add_image) if I don't need to use tensorboard??

**Comment by TontonTremblay** [comment]
I never understood how this error, and yes you can ignore it.

**Comment by hsisfree** [comment]
Thanks for your answer. I think this error came out from the code that store images at tensorboard. I checked that NaN and Inf is in "grid". But I tried with data made by nvisii, I also find NaN and Inf is grid too. I don't know why this errors came out with Fat data.

**Comment by TontonTremblay** [comment]
that would make sense. Thank you, anyway, it wont impact your network.
