### ISSUE TITLE
Not displaying image in Rviz

### ISSUE THREAD

**Issue by bjoshai** [NVlabs/Deep_Object_Pose#328]
$ roslaunch dope camera.launch 
there is no error with this
$  roslaunch dope dope.launch [config:=/path/to/my_config.yaml]
got a warning as this
  warnings.warn(
/home/cone/.local/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
  
  and i am getting topics as in pic
![Screenshot from 2023-11-03 10-53-11](https://github.com/NVlabs/Deep_Object_Pose/assets/139955757/b6ce35d9-b266-45f1-857d-a1694e8e2c68)

and  i am ruuning rviz after adding image i am not gettig image -NO IMAGE
![Screenshot from 2023-11-03 10-54-57](https://github.com/NVlabs/Deep_Object_Pose/assets/139955757/ceae44eb-a974-46a0-b694-ec71dced395b)

can anyone help me with this?

**Comment by TontonTremblay** [comment]
I cannot see the image topic you are seeing, if you have a little amount of experience with ros, I would recommend to do a few tutorials with ros and rviz. If DOPE is running correctly you will be able to select the topic on the menu on the left.

**Comment by bjoshai** [comment]
i am getting image but not other things
![Screenshot from 2023-11-04 10-29-34](https://github.com/NVlabs/Deep_Object_Pose/assets/139955757/a0741b7d-bbb4-4207-a56f-065be9c775c8)
help me in this

**Comment by TontonTremblay** [comment]
Which topic did you put?

**Comment by bjoshai** [comment]
![Screenshot from 2023-11-04 20-34-16](https://github.com/NVlabs/Deep_Object_Pose/assets/139955757/d32b99eb-5ea0-49a5-bf37-7f5257457636)
/rgb_points--->image

**Comment by TontonTremblay** [comment]
If you put a soup can now?

**Comment by bjoshai** [comment]
![Screenshot from 2023-11-05 16-56-16](https://github.com/NVlabs/Deep_Object_Pose/assets/139955757/0910dd42-ff31-47e5-87b4-cdc3ac936a65)
added the  images rgb_points and belief_soup image is they are visible after that i am not getting anything for pose and marker array .

**Comment by TontonTremblay** [comment]
everything seems to be working well :P but an object in front now that is the soup.

**Comment by bjoshai** [comment]
> everything seems to be working well :P but an object in front now that is the soup.

i didnt get ,could you please elaborate it?
Thanks

**Comment by bjoshai** [comment]
i didnt get ,could you please elaborate it?
Thanks

**Comment by TontonTremblay** [comment]
You need the physical object of a soup, google search an image of the tomato soup and point the camera at your screen.
