### ISSUE TITLE
  catkin_make error  ubuntu16

### ISSUE THREAD

**Issue by zkl99999** [NVlabs/Deep_Object_Pose#34]
$ apt-get install ros-kinetic-tf2
$ apt-get install ros-kinetic-cv-bridge
$ mkdir -p ~/catkin_ws/src   # Replace `catkin_ws` with the name of your workspace
$ cd ~/catkin_ws/
$ catkin_make
~/code/catkin_ws1$ /opt/ros/kinetic/bin/catkin_make -help
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/catkin_make", line 12, in <module>
    from catkin.init_workspace import init_workspace
ImportError: No module named catkin.init_workspace

**Comment by Dutzel** [comment]
I had the same issue. I fixed it by just following the installation guide in the link below:

http://wiki.ros.org/kinetic/Installation/Ubuntu

After typing "sudo apt-get install ros-kinetic-desktop-full" you should be able to use the "catkin_make"-command
