### ISSUE TITLE
render_json.py in scripts/metrics does not work as expected

### ISSUE THREAD

**Issue by wetoo-cando** [NVlabs/Deep_Object_Pose#348]
Trying to run the scripts/metrics/render_json.py as described under "Rendering 3d predictions using NViSII": https://github.com/NVlabs/Deep_Object_Pose/tree/master/scripts/metrics with

`python3 render_json.py --path_json ../nvisii_data_gen/output/dataset/003_cracker_box/000/00000.json --scale 1 --overlay --myobjectname 003_cracker_box --gray`

`nvisii_data_gen` generates the json file with objects of interest named as `"name": "single_obj_*` with `"class": "obj"`. So I've added the option `"--myobjectname"` to load the object of interest correctly. 

The JSON file:
[00000.json](https://github.com/NVlabs/Deep_Object_Pose/files/14775011/00000.json)

What I get is a grayscale output image named `overlay.png`, but without any cuboids rendered.

What could be wrong?

**Comment by TontonTremblay** [comment]
I think you are missing the 3d model you want to use. try removing the distractors. I think you are missing some downloads somehow, not sure how you set it up.

**Comment by wetoo-cando** [comment]
Thanks @TontonTremblay, yes seems to be a problem with paths to the 3D models.
