### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by joansaurina** [NVlabs/Deep_Object_Pose#359]
Hello.
I am running inference with mustard_60.pth and the detected cubes get this strange form. Do you know why is that? Could it be due to camera parameters?

![3-Figure1-1](https://github.com/NVlabs/Deep_Object_Pose/assets/121770607/977c5619-c908-4b7a-8bd0-ad52367d9bf3)
![4-Figure3-1](https://github.com/NVlabs/Deep_Object_Pose/assets/121770607/565c05ac-8c0f-4eb4-a4a2-c32e2dfd9ef8)

Thanks,
Joan

**Comment by TontonTremblay** [comment]
I think it is using the new model of cuboid3d, @nv-jeff made some changes to the repo, I had a "if" statement in the new inference code to use the old cuboid3d description. Maybe the update removed the if. It has been a while, https://github.com/NVlabs/Deep_Object_Pose/blob/c9f5aafd3f9f329ffc1ee922d2aa00f49d0a5c07/common/cuboid.py#L81 maybe this is the condition that is causing issues.

**Comment by nv-jeff** [comment]
I introduced a bug into `common/utils.py` during refactoring; the cuboid was drawn using the wrong vertex ordering. This has been fixed in checkin https://github.com/NVlabs/Deep_Object_Pose/commit/2e021c5f05727cbd5da47330a9c5ca37ef74fee5
