### ISSUE TITLE
Can I run this model using the pre-trained data sets using a low-end GPU (GTX1650 laptop)?

### ISSUE THREAD

**Issue by KennethEladistu** [NVlabs/Deep_Object_Pose#360]
Currently I want to try Deep Object Pose Estimation model with the given data sets. My laptop is only GTX1650 with 4gb ram  can it run this on my laptop's webcam using the pre-trained data?

**Comment by TontonTremblay** [comment]
Yeah I think you should be able to run it, if I remember the models loaded take 2gb of ram. Did you try?

**Comment by KennethEladistu** [comment]
> Yeah I think you should be able to run it, if I remember the models loaded take 2gb of ram. Did you try?

Yes but when I ran the model using "D:/Deep_Object_Pose/weights/pretrained_weights.pth" --data "D:/Deep_Object_Pose/sample_data" --object cracker this is what appeared:

![image](https://github.com/NVlabs/Deep_Object_Pose/assets/168053014/d1c03163-38c1-4d1b-86fe-4dc362ef4893)

**Comment by TontonTremblay** [comment]
I am not sure, there is an error with the detections happening here, @nv-jeff in your rework have you seen this?

**Comment by nv-jeff** [comment]
That is the result when you don't detect one or more cuboid vertices. If you examine the `points` array after it has been set from the `obj` data, you will see something like `[None, None, None, None, None, None, None, None, (349.0386957881619, 159.16052822031338)]`  

This looks like a bug to me, introduced from andrewyguo's changes.  I have pushed a fix as https://github.com/NVlabs/Deep_Object_Pose/commit/68534008dbc26b524272c00e6bef68b44d5e4b88

**Comment by mintar** [comment]
As an aside: 

> My laptop is only GTX1650 with 4gb ram can it run this on my laptop's webcam using the pre-trained data?

You won't have any problems with that. On one of my systems, I'm running DOPE on a GTX 1050 Ti 4GB without problems, and that GPU is even older than yours.
