### ISSUE TITLE
dope crashes in rviz 

### ISSUE THREAD

**Issue by AyeshaHabib** [NVlabs/Deep_Object_Pose#369]
Hello, I am able to see points for cuboid on belied map but the dope gave me error as shown in screenshot attached herewith. It crashed immediately. Kindly let me know what can be done about it [
![picture](https://github.com/NVlabs/Deep_Object_Pose/assets/64102302/e83492a8-4425-474b-aa01-58b00a13a58d)
](url)

**Comment by AyeshaHabib** [comment]
![Screenshot from 2024-06-25 02-43-28](https://github.com/NVlabs/Deep_Object_Pose/assets/64102302/883f0113-ae8c-4c5c-a7b8-fc41e8732b0e)

**Comment by nv-jeff** [comment]
This was caused by an old bug in the ROS1 version of `detector.py`.  It has been fixed in change https://github.com/NVlabs/Deep_Object_Pose/commit/e85dadb4016a18e1f2a83eb3febb0c1296673561

**Comment by AyeshaHabib** [comment]
worked, thank you so much
