### ISSUE TITLE
2024-07-08 01:26:43.797 ERROR gxf/std/program.cpp@551: Attempted interrupting when not running (state=0). [component_container_mt-1] 2024-07-08 01:26:43.798 ERROR gxf/core/runtime.cpp@1468: Graph interrupt failed with error: GXF_INVALID_EXECUTION_SEQUENCE

### ISSUE THREAD

**Issue by RenanMoreiraPinto** [NVlabs/Deep_Object_Pose#373]
Can you guys help me? 3 weeks ago was working fine with the setup i start training and finally got some results on inference so i can finally try on the  ros brigde but if i build from source it crash and dont show up the /poses topic and i cant build the version 3.0.1 of gxf from source if i get it from  the binary pack sudo apt-get install -y ros-humble-isaac-ros-dope there  a way to change the configs so i can add my new make file i try use my own .pth also the dope trained  weights can be use for the CenterPose? can you please guide me o this? 

i trying to follow the tutorial and build from source... everytime i build from source gxf give this error
2024-07-08 01:26:43.797 ERROR gxf/std/program.cpp@551: Attempted interrupting when not running (state=0).
[component_container_mt-1] 2024-07-08 01:26:43.798 ERROR gxf/core/runtime.cpp@1468: Graph interrupt failed with error: GXF_INVALID_EXECUTION_SEQUENCE

isaac_ros_common is on 3.0.1

**Comment by nv-jeff** [comment]
This doesn't look like an issue with the DOPE code. You may have better luck raising an issue with the Isaac ROS team here: https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/issues
