### ISSUE TITLE
How to test model accuracy

### ISSUE THREAD

**Issue by brumocas** [NVlabs/Deep_Object_Pose#386]
Hello again, I have been training DOPE on custom objects and I am  getting some results.
The model is the following:
![Screenshot from 2024-09-26 16-37-57](https://github.com/user-attachments/assets/ea67b4e4-893d-432f-8c85-c262ac8a464b)

The inference results are like the following images:
![00123](https://github.com/user-attachments/assets/d5a39670-525d-4f0d-b776-308f3b5ba0a2)
![00135](https://github.com/user-attachments/assets/aa98c9cd-e419-4189-878f-c6776628c9ec)
![00135](https://github.com/user-attachments/assets/092a1d49-d522-4d01-aa98-cc488e1c3480)
![00135](https://github.com/user-attachments/assets/55915745-58b9-4901-96d2-a601fa57ca22)
![00190](https://github.com/user-attachments/assets/acabe327-df58-4d8c-9e71-0491b13bfcc8)
![00205](https://github.com/user-attachments/assets/25d6c9fd-5bce-4967-b7ce-8fa853e58cdf)
![00299](https://github.com/user-attachments/assets/b2cfd1b2-d36d-441f-ad05-c7dad6b4aede)
![00331](https://github.com/user-attachments/assets/1229ae97-d4db-473f-8c23-d5b9567b4c9a)
![00379](https://github.com/user-attachments/assets/bf20972b-f420-4f3d-8578-3608729a22e7)

I want to implement this in a real robot application but first i need to evaluate model accuracy
How can I generate a dataset like the one you did for the cracker box, with ground truths?
Thanks in advance :)
![image](https://github.com/user-attachments/assets/1df6d86d-9ddc-4cf6-b6fd-f547de8dafa9)
![image](https://github.com/user-attachments/assets/fc664033-c42e-4bb1-9f87-baf5b1b85414)
![image](https://github.com/user-attachments/assets/d58f77f1-708d-4f3b-a302-15b9661b6068)
(...)

**Comment by TontonTremblay** [comment]
I wrote a script that in nvisii renders the data on a table like this. https://github.com/TontonTremblay/nvisii_mvs?tab=readme-ov-file#falling-object-scene I think this is what I used, there might be some options to make sure the object is upright.

**Comment by brumocas** [comment]
It worked for now :muscle: 
Really appreciate you help

**Comment by TontonTremblay** [comment]
Cool show me some renders you did :P would love to see more, I like when people are using my broken code I wrote :P

**Comment by brumocas** [comment]
Sure :)  
I managed to get the table and the object in the scene after playing around with the config.
The hdri background scene is not showing up for some reason, any idea to solve this?
Is the code only using the light from the hdri file?

![00000](https://github.com/user-attachments/assets/1384c233-df40-4acc-8783-761eb9811611)
![00030](https://github.com/user-attachments/assets/7120a595-64e6-4e83-9146-8bcdce5fb038)
![00058](https://github.com/user-attachments/assets/96a28b4b-c14c-42ab-93d4-faf44e7ab17f)

**Comment by brumocas** [comment]
Solved
