### ISSUE TITLE
Incomplete cuboid detection (Real hardware detection)

### ISSUE THREAD

**Issue by Tianyi20** [NVlabs/Deep_Object_Pose#388]
Hi, today i transfer my output training pth.file to hardware detection. My object is the red mug in YCB benchmark. However, when i set everything done to do detection, the result is very poor that can not detecte any object. And once very luckly it detecte the mug, a error occurs: 

Incomplete cuboid detection.   
result from detection: [None, None, None, None, None, None, None, None, (351.5094017726776, 92.23743706236147)]
Skipping.

![Screenshot from 2024-10-01 10-40-03](https://github.com/user-attachments/assets/8619590b-1629-4eee-be78-5de29912d1ab)

Furthermore, i would admit my training result is also very poor. Here I show my result for a several pictures:

![00016](https://github.com/user-attachments/assets/a25e8b04-edd2-4cab-a305-2a558b5e9128)

![00125](https://github.com/user-attachments/assets/8b9a65cd-519e-47ca-a435-7d93bc5bf001)

![00444](https://github.com/user-attachments/assets/5c340004-d82f-4c2a-be7a-6bb50f102d50)

![01874](https://github.com/user-attachments/assets/b7c5bdbf-4a33-474a-92d8-f9b129deaaf2)

Here is the command that generate data by nvisii_data_gen: 

$ **python single_video_pybullet.py --path_single_obj model/mug/textured.obj --scale 1 --nb_frames 10000 --nb_distractors 10 --nb_objects 25**

$ **python -m torch.distributed.launch --nproc_per_node=1 train.py --data /home/xiangtianyi/src/Deep_Object_Pose/data_generation/nvisii_data_gen/output/output_example --object obj --batchsize 10 --lr 0.001 --epochs 100**

Also I cannot assign correct  object class name in the output of data generation, it only appears to be "obj".

![Screenshot from 2024-10-01 10-53-33](https://github.com/user-attachments/assets/be32a0ad-0154-4c76-964d-e80352a02991)

 
Could give me any suggestions on these problems? I would be great appreciate!

**Comment by TontonTremblay** [comment]
ok wow yeah it is not looking too good, can you share some belief maps results? 

as for the class name, I think there is a split with the "." you might need to fiddle with this in the data generating script to get the right name.

**Comment by Tianyi20** [comment]
![Screenshot from 2024-10-02 09-38-02](https://github.com/user-attachments/assets/8180b367-d6fe-45f2-b041-fb3f53d18dc7)
![Screenshot from 2024-10-02 09-38-09](https://github.com/user-attachments/assets/f25f26c1-1b2a-4f9d-ad41-f499dc1ce74f)
![Screenshot from 2024-10-02 09-38-16](https://github.com/user-attachments/assets/811fef01-a150-4514-be3f-a033443bd369)
![Screenshot from 2024-10-02 09-38-27](https://github.com/user-attachments/assets/7b10d0f1-4868-4031-9356-55e67566458a)

Ah, it seems the result is pretty bad, sad。。

But do you have any suggestion ideas? I would appreciate your help!

**Comment by Tianyi20** [comment]
> ok wow yeah it is not looking too good, can you share some belief maps results?
> 
> as for the class name, I think there is a split with the "." you might need to fiddle with this in the data generating script to get the right name.


![Screenshot from 2024-10-02 09-38-02](https://github.com/user-attachments/assets/9765a3b6-faef-4ffa-951a-3f9575a8eb4c)
![Screenshot from 2024-10-02 09-38-09](https://github.com/user-attachments/assets/707544c0-947b-486f-937f-a615889618a2)

![Screenshot from 2024-10-02 09-38-16](https://github.com/user-attachments/assets/0cf56441-2b63-453a-b4f6-23611092f482)
![Screenshot from 2024-10-02 09-38-27](https://github.com/user-attachments/assets/70bc9e94-2c6b-467b-84c4-71f70cf1dd1f)

It doesn't look well. Sad
Could you help me about it?

**Comment by TontonTremblay** [comment]
It looks good to me, the points it found are well around the mug, the data you have, I think the mugs are getting too big in the image. Also the mug is symmetrical when you are not seeing the handle, but it does not look too problematic. Also I thought that mug was red. is it not?

**Comment by Tianyi20** [comment]
> It looks good to me, the points it found are well around the mug, the data you have, I think the mugs are getting too big in the image. Also the mug is symmetrical when you are not seeing the handle, but it does not look too problematic. Also I thought that mug was red. is it not?

Thank you for your reply. But what do you mean the mug are getting too big in the image? Does it means I need to shrink the ' --scale 1" in video generation.py?Also the mug is in red color, does it have any problem needed to be fixed?

**Comment by TontonTremblay** [comment]
I am sure if you generate a dataset with like 2-3 mugs and change the the plane locations to be further away, your weights would work just fine, did you try on a webcam?

**Comment by Tianyi20** [comment]
> I am sure if you generate a dataset with like 2-3 mugs and change the the plane locations to be further away, your weights would work just fine, did you try on a webcam?

I will try to do this. I used to use realsesne DB435 camera but only use colour stream. It can detect sugar, catchup with the weights that you have trained very well. But it cannot even detect the mug in an entire cuboid. sad

**Comment by Tianyi20** [comment]
> I am sure if you generate a dataset with like 2-3 mugs and change the the plane locations to be further away, your weights would work just fine, did you try on a webcam?

By the way, how to change the the plane locations to be further away？

**Comment by TontonTremblay** [comment]
can you check the belief on the webcam? 

https://github.com/NVlabs/Deep_Object_Pose/blob/master/data_generation/nvisii_data_gen/single_video_pybullet.py#L252-L255 check the -2 I think, play with that.

**Comment by Tianyi20** [comment]
hi, sorry for the delay response. But I still have problem about detecting my object, red mug. The dope can publish nothing about the dimension about the mug. However, i find the belief map is quite good.

![Screenshot from 2024-10-05 02-51-31](https://github.com/user-attachments/assets/9395f7fc-135f-417c-8b8f-ee206cd4d2aa)

**Comment by Tianyi20** [comment]
Here is my temporary training result. And the training is till going.

![Screenshot from 2024-10-04 14-53-57](https://github.com/user-attachments/assets/268265bc-528d-4f05-9b07-a4ab06872489)
![Screenshot from 2024-10-04 14-54-10](https://github.com/user-attachments/assets/2c8e198e-8ca3-4d62-b294-178a22ddff4b)
![Screenshot from 2024-10-04 14-54-16](https://github.com/user-attachments/assets/25ca4745-8f6b-44e6-968a-20385e99e932)
![Screenshot from 2024-10-04 14-54-25](https://github.com/user-attachments/assets/a716769b-6fee-4fa6-8e5b-a53368b18658)

**Comment by Tianyi20** [comment]
But i can really well detect the sugar, is there something important to publish data that i forget to do?
![Screenshot from 2024-10-05 03-01-35](https://github.com/user-attachments/assets/1933a8e9-dc27-4acf-985b-935c839c7b0c)

**Comment by Tianyi20** [comment]
I have also changed the texture.obj to let it make more sense. The detection output is OK. Here is an output. But why i can't detect anything when move to the hardware camera?


![Screenshot from 2024-10-05 05-52-47](https://github.com/user-attachments/assets/e0db2d76-5df4-4e5a-a6d8-9301b88abfa4)

**Comment by Tianyi20** [comment]
@TontonTremblay Hi, could you help me with that? I will be a lot of appreciate!

**Comment by TontonTremblay** [comment]
yeah this looks good, I think the real world test you tried your object might be too close to the camera, did you try moving it out a little bit more? Also make sure you show it with the handle! I am not sure how to interpret the results on the real world mug, the beliefs are clearly not correct, when I have seen this in the past it was somewhat confusing the symmetries and or too close to the camera.

**Comment by Tianyi20** [comment]
> yeah this looks good, I think the real world test you tried your object might be too close to the camera, did you try moving it out a little bit more? Also make sure you show it with the handle! I am not sure how to interpret the results on the real world mug, the beliefs are clearly not correct, when I have seen this in the past it was somewhat confusing the symmetries and or too close to the camera.

Thank you for your reply. But it nearly cannot output anything. Sad...

![Screenshot from 2024-10-05 06-13-29](https://github.com/user-attachments/assets/e49a96a2-f81b-443d-9d4c-235357d038fa)

**Comment by Tianyi20** [comment]
> > yeah this looks good, I think the real world test you tried your object might be too close to the camera, did you try moving it out a little bit more? Also make sure you show it with the handle! I am not sure how to interpret the results on the real world mug, the beliefs are clearly not correct, when I have seen this in the past it was somewhat confusing the symmetries and or too close to the camera.
> 
> Thank you for your reply. But it nearly cannot output anything. Sad...
> 
> ![Screenshot from 2024-10-05 06-13-29](https://private-user-images.githubusercontent.com/131247591/373819111-e49a96a2-f81b-443d-9d4c-235357d038fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODAzNTMsIm5iZiI6MTcyODA4MDA1MywicGF0aCI6Ii8xMzEyNDc1OTEvMzczODE5MTExLWU0OWE5NmEyLWY4MWItNDQzZC05ZDRjLTIzNTM1N2QwMzhmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQyMjE0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTNiM2U0Mjg2NTQxZWYxZWIwYTI0M2I1MGE1YzVhZWIzMGJjZjMwMjQ2OTFlMGI2MTIxZjdmMzViNTUxMjE5JlgtQW16LVN

![Screenshot from 2024-10-05 06-16-07](https://github.com/user-attachments/assets/f6222750-d6d0-426f-aff6-32a11b997fc8)
pZ25lZEhlYWRlcnM9aG9zdCJ9._FYYmEjHgLauCBYbrz-UZQ4i5vKnKE4KD4jcFsXPL4Q)

**Comment by TontonTremblay** [comment]
hummm I would think the model did not train long enough, you are seeing good results on the training data though?

**Comment by Tianyi20** [comment]
> hummm I would think the model did not train long enough, you are seeing good results on the training data though?

Here is the output on the training data. By the Inference.py.

![00006](https://github.com/user-attachments/assets/5f2e73a9-23c5-4efe-9ac3-a73ff435d739)
![00007](https://github.com/user-attachments/assets/66774e0c-fb79-4a1d-a58d-76d66c848bcc)
![00008](https://github.com/user-attachments/assets/ca98d152-46a2-49c9-849a-e5173e2c50b0)

![00004](https://github.com/user-attachments/assets/28efcfa1-bee1-4122-9319-b59229353a69)
![00005](https://github.com/user-attachments/assets/58dbff29-7d62-48f7-8863-e7fb14c7dfda)

**Comment by Tianyi20** [comment]
> hummm I would think the model did not train long enough, you are seeing good results on the training data though?

Sad, but i am really in hurry to use this detection output. I don't know why your weights to the sugar can work but my weights to the mug cannot work given that it can detect the mug in inference.py. But... Could you help me training this mug?  I can give you the YCB link to this mug's data...

**Comment by TontonTremblay** [comment]
I would love to help more than just providing insights, but I am sorry, I cannot do much more than that. The results you got on the training data are very encouraging, maybe try with different light, maybe more?

**Comment by Tianyi20** [comment]
@TontonTremblay Dear Tonton, i can say the problem is too less background pictures that are used for training. I find the inference can only works on the specific one background used for training. Maybe the data generation part should add more background pictures like your papers write that you use nearlly 10,000 background pictures for training. But really thanks to your help! And I'd like to say dope is an amazing work as long as you have enough computational source. HHH

**Comment by TontonTremblay** [comment]
that makes sense, https://drive.google.com/file/d/1lp36MgTlS4OFaH0vdsTFhyGFJpQDY2YX/view?usp=sharing here are more background, I was under the impression you used more than that one background.

**Comment by TontonTremblay** [comment]
I think there is 1000 backgrounds
