### ISSUE TITLE
Failed detected

### ISSUE THREAD

**Issue by QuanNguyen94** [NVlabs/Deep_Object_Pose#4]
I load cracker_60.pth checkpoint and try the below image, but have no cube detected. The result list is empty, and I have tried showing belief maps and affinity maps but they look fail. Do you have any ideas about this, can you explain more about affinity map pls ?
![test3](https://user-images.githubusercontent.com/15965347/48521342-ad080800-e8a6-11e8-9ed8-bfcece277c57.jpg)
![1](https://user-images.githubusercontent.com/15965347/48521345-b1342580-e8a6-11e8-9b1e-5d11e8b7d5e8.png)

**Comment by TontonTremblay** [comment]
I would say that the problem comes from the texture on the cracker box not being the same as the one we are using to train our model. Can you try to point the camera to your monitor with an image of the actual cracker box we used? Also the belief maps look pretty bad, I would think the top vertexes should react to the label. 

The affinity maps are used to find multiple instances of the same object. Technically for this release they are not essential assuming there is only one object of that type in the scene.

**Comment by TontonTremblay** [comment]
try this one: https://www.google.com/search?q=cheez+it+original&safe=active&rlz=1C1GGRV_enUS764US765&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiiyf6WltXeAhVcIjQIHW-RAeIQ_AUIDygC&biw=1745&bih=917#imgrc=sR9i3ISjk3rFGM:

**Comment by QuanNguyen94** [comment]
![test4](https://user-images.githubusercontent.com/15965347/48523007-38849780-e8ad-11e8-9db3-a243eb58d140.jpg)
I have try this one, but got the same issue. Can you give me a specific image you used ?

**Comment by QuanNguyen94** [comment]
![result](https://user-images.githubusercontent.com/15965347/48529486-e4d27800-e8c5-11e8-9d77-b01540108752.png)
![1](https://user-images.githubusercontent.com/15965347/48529583-57435800-e8c6-11e8-8a70-4e1872427e13.png)
Thank for your sharing, I have tried it. Is this result looks good ?
Some more question pls, i wonder how you label for affinity maps and is there any special things in loss function, or just use L2 loss of BeliefMap and AffinityMap with groundtruth ?

**Comment by ZWYDeveloper** [comment]
> ![cube](https://user-images.githubusercontent.com/15965347/48537681-e2cbe180-e8e4-11e8-8936-e07164fda29f.png)
> ![1](https://user-images.githubusercontent.com/15965347/48529583-57435800-e8c6-11e8-8a70-4e1872427e13.png)
> Thank for your sharing, I have tried it. Is this result looks good ?
> Some more question pls, i wonder how you label for affinity maps and is there any special things in loss function, or just use L2 loss of BeliefMap and AffinityMap with groundtruth ?

Hello!

How do you achieve the effect of dope in your own camera? I compiled it smoothly, but I can't get the image, or I can't achieve the desired effect in the ROS camera. Can you help me? Thank you!

**Comment by QuanNguyen94** [comment]
Hello bro,
I didnt setup the camera yet so I cannot say anything about your question.

**Comment by TontonTremblay** [comment]
What I am seeing is correct, this is the expected behaviour. We simply use L2 on the maps, you are correct. There is no special loss.

**Comment by QuanNguyen94** [comment]
Thank you @TontonTremblay, that 's all. You and your team had a great work :D

**Comment by Abdul-Mukit** [comment]
Hi guys, here is my code for visualizing the feature maps. The detector is provided by DOPE. Hope it helps.
`
import cv2
import matplotlib.pyplot as plt
import torch
from detector import *

## Settings
name = 'mustard'
net_path = 'data/net/mustard_60.pth'
# net_path = 'data/net/cautery_s6_60.pth'
gpu_id = 0
img_path = 'data/images/cautery_DR_2.png'
# img_path = 'data/images/cautery_real_1.jpg'



# Function for visualizing feature maps
def viz_layer(layer, n_filters=9):
    fig = plt.figure(figsize=(20, 20))
    row = 1
    for i in range(n_filters):
        ax = fig.add_subplot(4, 5, i + 1, xticks=[], yticks=[])
        # grab layer outputs
        ax.imshow(np.squeeze(layer[i].data.numpy()), cmap='gray')
        ax.set_title('Output %s' % str(i + 1))

# load color image
in_img = cv2.imread(img_path)
# in_img = cv2.resize(in_img, (640, 480))
in_img = cv2.cvtColor(in_img, cv2.COLOR_BGR2RGB)
# plot image
plt.imshow(in_img)


model = ModelData(name, net_path, gpu_id)
model.load_net_model()
net_model = model.net

# Run network inference
image_tensor = transform(in_img)
image_torch = Variable(image_tensor).cuda().unsqueeze(0)
out, seg = net_model(image_torch)
vertex2 = out[-1][0].cpu()
aff = seg[-1][0].cpu()

# View the vertex and affinities
viz_layer(vertex2)
viz_layer(aff, n_filters=16)

plt.show()

`

**Comment by Abduoit** [comment]
Thanks @Abdul-Mukit , do you know how to print the output of the vertices (position of vertices), to show the centroids of the object.

**Comment by liangzhicong456** [comment]
@Abdul-Mukit thanks for your great job! I have seen your recent work posted to youtube which detected pen. Thus, I am eager to know how do you create the pen model and get the dataset by NDDS? Hope for your reply, sincerely!
PS: as far as I know, can MAYA and substance painter get the model, but not for sure.

**Comment by Abdul-Mukit** [comment]
> Thanks @Abdul-Mukit , do you know how to print the output of the vertices (position of vertices), to show the centroids of the object.

Sorry, didn't try that. I think you can find the required code if you look into the original codes.

**Comment by Abdul-Mukit** [comment]
> @Abdul-Mukit thanks for your great job! I have seen your recent work posted to youtube which detected pen. Thus, I am eager to know how do you create the pen model and get the dataset by NDDS? Hope for your reply, sincerely!
> PS: as far as I know, can MAYA and substance painter get the model, but not for sure.

@liangzhicong456  Thanks for checking out the videos. The model was created in blender. But you can use MAYA too, I think. Then you have to import just the mesh as fbx (nothing else worked for me). Then in UE4, you add different materials to different parts of your 3d model. Hope that helps. BTW just out of curiosity, what object are you trying for?

**Comment by liangzhicong456** [comment]
@Abdul-Mukit Thanks for your reply, I want to create the tissue model, but the complex surface texture makes me unable to start which the texture information is very important for detection. So I really want to know how I can get more accurate model and texture information. I have known Blender before, but can get accurate model? I want to know that all the information inside is hand-painted, including models and textures? I am a beginner and may have some stupid questions, hope for your patient answer.

**Comment by Abdul-Mukit** [comment]
@liangzhicong456 I am a beginner myself, It's just been 5 months since I started my project :)
From the image, it looks to me hand-designing the texture is too difficult. You need UV maps for texture. If I were you, I guess I would try to load the YCB objects (the objects used in DOPE) in NDDS. You will need to learn how to load UV maps along with mesh I think. You will need to do something similar for your tissue box.
If you don't want to go for a 3D scan then you can try to create a UV map or a texture map by slicing the packaging of the tissue box then taking pictures of it. I think it should be possible. I saw some tutorials about UV mapping and it appears to me UV maps will solve your problem.

**Comment by liangzhicong456** [comment]
@Abdul-Mukit Thanks for your suggestion. I found that Blender combined with UV map can get the effect I want. I am studying hard now, hope for keeping communication with you, thanks sincerely！

**Comment by Abdul-Mukit** [comment]
@liangzhicong456 you can email me in my email address instead of lengthening this issue.

**Comment by liangzhicong456** [comment]
Ok，thank you very much for your help！

**Comment by TontonTremblay** [comment]
The output you are getting is similar to what I would think you should get. The pepsi can you have has some almost symmetries, which explains why output 8 is kind of multi-modal. I dont think you can avoid the confusion with the sprite can as the colors and top are very similar. The way you visualize the affinity field is just miss leading, you should display them as color wheels. 
![00000_aff](https://user-images.githubusercontent.com/5629088/63952577-b11ba580-ca34-11e9-8f2c-2581cf15bf79.png)

The color shows the direction of the vector and you will have to ignore everything that is close to zero in magnitude.

**Comment by aditya2592** [comment]
Thanks for the suggestion @TontonTremblay. After some tweaks I am getting the 3D bounding box correctly as below : 
![test](https://user-images.githubusercontent.com/2186078/63963758-b93f0980-ca63-11e9-8535-56143ad11d0b.png)
However, the depth (z coordinate in camera frame) was off by 10-12 cm. That was fixed when I changed the downscale height to 400 (the height the network was trained on)

**Comment by TontonTremblay** [comment]
This is awesome, I am glad you were able to get good results :P. Yeah you have to be careful with image size when running the algorithm.

**Comment by jediofgever** [comment]
Hi, I have exactly same problem. the activation maps  seems to be activated but the dope node detects nothing on the image. I tried to convert bgr to rgb when reading image through opencv, resized the image but still the object is not being detected. What else could be problem ?
![Screenshot from 2019-10-15 22-38-14](https://user-images.githubusercontent.com/18460336/66806355-e7b46d80-ef59-11e9-9111-3fa1384812b1.png)

**Comment by TontonTremblay** [comment]
Lets try to run DOPE with a lower threshold. 

https://github.com/NVlabs/Deep_Object_Pose/blob/1ee8e0ddaa01886785ba176581582947008440d4/src/dope/inference/detector.py#L314 

https://github.com/NVlabs/Deep_Object_Pose/blob/1ee8e0ddaa01886785ba176581582947008440d4/src/dope/inference/detector.py#L366

You can change those values in the config file. Play around with some values and let me know what  you are getting.  

I think I am going to provide a debug view for the affinity maps. I cannot read the values you are displaying.

**Comment by akeaveny** [comment]
Hi @Abdul-Mukit, I am attempting to visualizing the feature maps but I am unable to run your script as a stand alone file. The error I can't get past is 

`Traceback (most recent call last):
  File "./visualize.py", line 7, in <module>
    from detector import *
ModuleNotFoundError: No module named 'detector'
`

**Comment by Abdul-Mukit** [comment]
@akeaveny you need to put detector.py in the same directory as your code. You can find the detector.py file in DOPE.

**Comment by akeaveny** [comment]
@Abdul-Mukit ahh, thanks! Got it running now

**Comment by akeaveny** [comment]
@jediofgever were you able to resolve your issue? I'm facing the same problem

**Comment by Abdul-Mukit** [comment]
@QuanNguyen94 hi again.
I am trying to generate the affinity map visualization using color wheels as you commented above. [link](https://github.com/NVlabs/Deep_Object_Pose/issues/4#issuecomment-526231362).
Could you please tell me how you generated those plots?
