### ISSUE TITLE
NDDS Question: Unreal engine interface angles to the rotation exported json 

### ISSUE THREAD

**Issue by MohamadJaber1** [NVlabs/Deep_Object_Pose#42]
Hello,

First of all, thanks for sharing this amazing work!

Secondly, using **NDDS**, I would like to know the convention used to export the rotation matrix in the images _json_ files.

![000001](https://user-images.githubusercontent.com/48984186/57845961-6fdbee80-77d3-11e9-8a6d-6b795311df7d.png)

Here, the rotation angles in unreal engine interface are **[0, 0, -90]**. So I know that they have been exported in a way as OpenCV expects where each has a different coordinate system #28. For the translation vector, I knew how it has been ordered but for the rotation matrix being exported in the json file which is **[[-1 0 0][0 0-1][0 1 0]]**. So, I am trying to infer from this rotation matrix then angles to represent the same position of the object as shown above.  I tried calculating them but its not matching.

Thank you once again, looking forward for your reply.

**Comment by TontonTremblay** [comment]
I dont remember exactly and the dev for NDDS is on vacation this week and the next one. Could you not just use the quaternion and then create a rotation matrix out of it to double check it?  

We also released a tool to visualize the data from NDDS, you can probably find your answer somewhere in there (https://github.com/NVIDIA/Dataset_Utilities). 

Just for fun, could you share the json file and the _camera_setting.json and the _object_setting.json?

**Comment by MohamadJaber1** [comment]
Thank you for your reply @TontonTremblay

I will try looking into it. It caused me headache trying to figure out the convention used to export this rotation matrix. 

The rotation angles given at unreal engine interface are [0 0 90] degrees. 

 _Camera_setting.json
![CameraSettings](https://user-images.githubusercontent.com/48984186/57924524-979b8700-78a5-11e9-8525-61ae4e7f7357.JPG)
_object_setting.json
![ObjectSettings](https://user-images.githubusercontent.com/48984186/57924529-9e29fe80-78a5-11e9-848d-973bd5f22f96.JPG)#

000000.json (**note that the second column of the rotation matrix is different from that of the object settings one**)
![JsonSettigns](https://user-images.githubusercontent.com/48984186/57924555-ae41de00-78a5-11e9-8b41-c600fd29d5ee.JPG)

Hope it is possible to infer the rotation angles from the above rotation matrix. Thanks.

**Comment by MohamadJaber1** [comment]
Quaternions solved my problem, thanks a lot :smile:

**Comment by SoumyaViralint96** [comment]
Hi, all i have a doubt can we extract all the features at a time for a dynamic object.

bcz when I try to extract all the data the textures information is missing on the meshes. 

please I need help!

Thanks.. 
![Capture](https://user-images.githubusercontent.com/74580325/104914579-5aaa6080-59b5-11eb-85ca-6fb420a67e51.PNG)

**Comment by thangt** [comment]
```when I try to extract all the data the textures information is missing on the meshes.```
What information is missing? Can you show us some images of this problem? 
Also can you create a new thread since your question doesn't seem to fit this issue.

**Comment by SoumyaViralint96** [comment]
Hi, I am having issues with the exported images using NDDS. Upon exporting, the texture/color of the object is missing whenever I try to also export depth, segmentation masks, etc. The colors are only exported properly when the True color option is selected.
image
Here is a sample of the resulting image.
000037

When all data are selected the exported image becomes like this:
000009

Can you help me in fixing this problem?

Thanks.

**Comment by SoumyaViralint96** [comment]
Hi, I am having issues with the exported images using NDDS. Upon exporting, the texture/color of the object is missing whenever I try to also export depth, segmentation masks, etc. The colors are only exported properly when the True color option is selected.
![105278963-8b6edd80-5be1-11eb-9e82-ec68b7cae562](https://user-images.githubusercontent.com/74580325/106085604-86acab00-6146-11eb-8420-494d276d8be9.png)

Here is a sample of the resulting image.

![105278910-6b3f1e80-5be1-11eb-876b-ed94993ca8b9](https://user-images.githubusercontent.com/74580325/106085640-94623080-6146-11eb-9863-80c58dbe94e6.png)

When all data are selected the exported image becomes like this:
![105279104-d25cd300-5be1-11eb-852b-1beb37bd27ab](https://user-images.githubusercontent.com/74580325/106085660-9d530200-6146-11eb-981b-19d79d6024d3.png)

Can you help me in fixing this problem?

Thanks.
