### ISSUE TITLE
NDDS Multi-viewpoints capturer export the exact replicated images

### ISSUE THREAD

**Issue by zhezhou1993** [NVlabs/Deep_Object_Pose#51]
The stereo images captured by multi-viewpoints capturer (e.g. Zed capturer) are identical. From the preview window, the different viewpoints looks correct but the exported images are wrong. The multi-viewpoints components not working as expected.

**Comment by thangt** [comment]
Fixed by commit: https://github.com/NVIDIA/Dataset_Synthesizer/commit/de83376d237adc29e312ba8011fdc7d7394f3490
