### ISSUE TITLE
NDDS error on TestCapturer.umap

### ISSUE THREAD

**Issue by baljit92** [NVlabs/Deep_Object_Pose#53]
When I try to build and launch NDDS: I get an error saying "TestCapturer.umap is an asset" I've added a screenshot along. In addition to that, there is no SimpleScene_Capture under NVSceneCapturer Content.

Are these two issues related? Also, is this issue because of the new NDDS update? I'm using Unreal 4.22.3 on Fedora

![Screenshot from 2019-07-11 15-13-41](https://user-images.githubusercontent.com/5225501/61049958-82972c00-a3ee-11e9-8c88-923c8ef3842b.png)

**Comment by thangt** [comment]
Can you check the TestCapturer.umap in the disk to see how big it is? This problem may happen if you don't use git LFS, which will cause LFS files to be just a text file.

**Comment by baljit92** [comment]
Yes. That was the problem. Thank you!
