### ISSUE TITLE
multiple object for config file

### ISSUE THREAD

**Issue by liangzhicong456** [NVlabs/Deep_Object_Pose#57]
I have already entered the hybrid training for mixed dataset, but I don't know how to write config with multiple object when I test. Hope for someone help，thanks！
PS: found that the provided config file is one object.

**Comment by TontonTremblay** [comment]
Did you train on new objects? If so you need to add the weights to the `config/config_pose.yaml`. Make sure to add `weights` path, normally we put them in the weights folder, `class_ids`, `dimensions`, and there are more if you want the 3d model loaded in rviz.

**Comment by zhangstar3** [comment]
@liangzhicong456 Hello,I'm also training my own model. Is it convenient for communication? and leave a  email to contact 2561612514@qq.com
