### ISSUE TITLE
Run multiple DOPE ROS Nodes each on a different camera

### ISSUE THREAD

**Issue by dj4park** [NVlabs/Deep_Object_Pose#63]
Is there a way to run multiple DOPE nodes each on a different camera?

I have two ZED cameras that are connected to the same computer. Each of these cameras are on top a table that are 15ft apart. I would like both cameras to detect an object. 

I am using a single ROS master on my computer. How can I run two instances of DOPE at the same time?

**Comment by TontonTremblay** [comment]
It should be pretty straight forward to do. You will have to create two config files in the config folder. Lets assume for both cameras you are running the pose estimation in the left eye or rgb ros topic and that you are running multiple zed cameras launch file (https://github.com/stereolabs/zed-ros-wrapper/blob/master/zed_wrapper/launch/zed_multi_cam.launch). 

Then in the first config, lets say `config_pose_zed1.yaml` file change the following:
```
topic_camera: "/zed1/zed_node/rgb/image_rect_color"
topic_camera_info: "/zed1/zed_node/rgb/camera_info"
topic_publishing: "dope_zed1"
input_is_rectified: False # since you are using the rect topic
```
Now change zed 1 to zed 2 in the other file. After that you can run dope twice each with the right config file. 

I hope this helps
