### ISSUE TITLE
Evaluation Metric Used

### ISSUE THREAD

**Issue by aditya2592** [NVlabs/Deep_Object_Pose#67]
Hi

The DOPE paper mentions that ADD metric has been used to measure performance for the 5 objects. Does this mean that ADD and not ADD-S has been used for all 5 even in cases where the object is symmetric?

**Comment by mintar** [comment]
I'm not an author of the paper, but yes, the normal ADD metric has been used, because the objects are not symmetric. Even though the shape of some objects has some symmetries, the texture is different on all sides, so the 6DoF pose is unambiguous.
