### ISSUE TITLE
[A simple question] Transformation between DOPE 3D-model and YCB 3D-model?

### ISSUE THREAD

**Issue by trevor-taeyeop** [NVlabs/Deep_Object_Pose#72]
Hi, TontonTremblay

Thank you for sharing this great work!

I have a simple question for your work.
- **What is the transformation between DOPE 3D-model and YCB 3D-model?**

When I try to visualize the DOPE with YCB 3D-model, I figured out that the 3D-model (i.e., 3D bbox with 8 corner-points in your work) was in different pose compared to the 3D-model from YCB dataset. Specifically, when I visualized both two types of 3D-models using pose learned from the DOPE, I observed that the main difference was rotation. But I couldn't figure out the exact transformation of it.

It would be appreciated If let me know ! :)

Best regards.

**Comment by mintar** [comment]
You can find the transformations here:

https://github.com/NVIDIA/Dataset_Utilities/blob/532b8c76e3d7946748a10af3398438b35383f157/nvdu/config/object_settings/_ycb_original.json

It's best to use the [nvdu tool](https://github.com/NVIDIA/Dataset_Utilities) to download and transform the YCB meshes. Afterwards, you can use the meshes in the `aligned_cm` directory for visualization by commenting in the respective lines here:

https://github.com/NVlabs/Deep_Object_Pose/blob/master/config/config_pose.yaml#L61
