### ISSUE TITLE
UE4 Environment for creating a dataset?

### ISSUE THREAD

**Issue by TrinhTUHH** [NVlabs/Deep_Object_Pose#81]
Hi @TontonTremblay ,
I am trying to creating a similar dataset but with my own objects. In the paper, you mentioned that you used the virtual environment such as kitchen, sun temple, forest, etc. for their high fidelity. Could you please share the links to these environments? Thank you in advance!

**Comment by thangt** [comment]
Hi @TrinhTUHH,

Here is how you get the SunTemple scene: https://github.com/NVlabs/Deep_Object_Pose/issues/45#issuecomment-502304956

We bought the kitchen scene from here: https://www.unrealengine.com/marketplace/en-US/slug/archviz-kitchenette

The forest scene is from here: https://www.unrealengine.com/marketplace/en-US/slug/open-world-demo-collection

**Comment by TrinhTUHH** [comment]
Thank you very much Thang To!
