### ISSUE TITLE
How to use baxter to grasp?

### ISSUE THREAD

**Issue by qingchenkanlu** [NVlabs/Deep_Object_Pose#83]
I have got the 6d pose in camera frame, after calibration I get the pose in baxter base frame, but when I use baxter_core_msgs SolvePositionIK , I can not get valid IK solution. I want to ask how you solve IK problem?

**Comment by TontonTremblay** [comment]
I am sorry I am not sure how to help you, I am not that good with baxter.

**Comment by qingchenkanlu** [comment]
Thanks, I have solved the problems!

**Comment by diaodeyi** [comment]
Hi , excuse me, i want to konw how to use baxter to grasp when i got the 6d pose in camera frame.
