### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by cianohagan** [NVlabs/Deep_Object_Pose#89]
I have created custom objects with the UE4 repository and have trained the neural network on the custom object dataset to predict the affinity and belief maps from a query image. The dataset contains only one object.

My question relates to the object detection / pose estimation after the the NN has predicted the keypoints. In config_pose.yaml, there is a comment that reads 'Comment any of these lines to prevent detection / pose estimation of that object' above the dictionary containing paths to weights files for objects in the Falling Things dataset. My questions are:
- What are these *.pth files?
- Why are these weights files necessary for object detection? 
- Can these files be created with the UE4 repository? 
- Are they needed for the step that predicts the object that each belief map belongs to?

Thanks

**Comment by TontonTremblay** [comment]
Sure let me clarify things. 
- **What are these *.pth**
A pth file is what pytorch uses to save a set of weights. If you check your `train_my_obj/` created by the training scripts you should see something like `net_epoch_1.pth, net_epoch_2.pth ... net_epoch_N.pth` where N is the number of epoch trained for. Rename the last one to something like my_obj.pth and move it inside the DOPE `weights` folder. Then in the config please add a line similar to the other ones. Then you need to add the dimensions of the object. Just look at the dataset you generated with NDDS, there is a file called _object_settings.json. Inside you can find your object dimensions. Copy and paste them, be careful they might be in different dimensions, e.g. mm vs cm.   

- **Why are these weights files necessary for object** 
This is what is used by pytorch to produce predictions. 

- **Can these files be created with the UE4** 
They could, we are always happy to receive PR. :P 

- **Are they needed for the step that predicts the object that each belief map belongs to?**
Yes! Please refer to the first question for more detailed answer.

**Comment by cianohagan** [comment]
Thanks
