### ISSUE TITLE
Visualization in ROS

### ISSUE THREAD

**Issue by aditya2592** [NVlabs/Deep_Object_Pose#9]
Hi

What is the reason behind adding a rotation between world and dope transforms as stated below in the README? -

```rosrun tf static_transform_publisher 0 0 0 0.7071 0 0 -0.7071 world dope 10```

If we have our own TF setup between ```/world``` and ```/camera_link```, can we use that directly instead of creating a ```dope``` frame?

**Comment by TontonTremblay** [comment]
You are correct if you have your own frame you do not need this. Please change the frame in the config file.
